# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_auto_20160828_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottommenuitem',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bottommenuitem',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mainmenuitem',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainmenuitem',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
