# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.HTMLContent'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
