# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20160827_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
