# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20160827_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('href', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, choices=[('Organizator', 'Organized by'), ('Collaborator', 'In collaboration with'), ('Cooperator', 'In cooperation with'), ('Accomodation', 'Accommodation and Travel by'), ('Supporter', 'Main supporters:')], default=None, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Page'),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
