# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20160828_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.HTMLContent'),
        ),
    ]
